client/urls.py
from django.urls import path
from .views import (
    TokenListView, 
    TokenDetailView, 
    TokenCreateView, 
    TokenUpdateView, 
    TokenDeleteView,
    UserTokenListView,
    ProfileView,
    ClientProfileUpdateView,
    UserUpdateView
)
from . import views

app_name = 'client'

urlpatterns = [
    path('', TokenListView.as_view(), name='token-home'),
    path('token/', UserTokenListView.as_view(), name='token-list'),
    path('token/<int:pk>/', TokenDetailView.as_view(), name='token-detail'),
    path('token/new/', TokenCreateView.as_view(), name='token-create'),
    path('token/<int:pk>/update/', TokenUpdateView.as_view(), name='token-update'),
    path('token/<int:pk>/delete/', TokenDeleteView.as_view(), name='token-delete'),
    path('profile/', ProfileView.as_view(), name='user-profile'),
    path('profile/user-update/', UserUpdateView.as_view(), name='user-update'),
    path('profile/profile-update/', ClientProfileUpdateView.as_view(), name='user-profile-update'),
    path('about/', views.about, name='token-about'),
]

slot_management/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from client import views as client_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('client.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login/', user_views.CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    # path('profile/', user_views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# from django.urls import path
# from . import views

# urlpatterns = [
#     path("api/get_subroles/", views.get_subroles, name="get_subroles"),
# ]

tokenapp/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from users.models import CustomUser
from django.urls import reverse


class Service(models.Model):
    name = models.CharField(max_length=255, unique=True, primary_key=True)
    code = models.CharField(max_length=10, null=True)
    is_default = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        if self.name == 'Other':
            self.is_default = True
            self.code = 'OTH'
        if self.is_default:
            if Service.objects.filter(name='Other', code='OTH').exists():   
                return 
        super(Service, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.is_default and self.name == 'Other' and self.code == 'OTH':
            return
        super(Service, self).delete(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=20, unique=True, primary_key=True)
    description = models.TextField(null=True, blank=True)
    
    
class StatusHistory(models.Model):
    tracked_object = models.ForeignKey('Token', on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    timestamp = models.DateTimeField(auto_now_add=True)


class Token(models.Model):
    token_date = models.DateField(default=timezone.now)
    token_time = models.TimeField(default=timezone.now)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, related_name='tokens_for_service')
    custom_service = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True)
    is_booked = models.BooleanField(default=False)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, related_name='tokens_created_by_user')
    token_modified = models.DateTimeField(auto_now_add=True)
    assigned_staff = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='tokens_assigned_to_staff')
    status = models.ForeignKey(Status, on_delete=models.PROTECT, related_name='tokens_with_status' ,default='Pending')
    status_was = models.ForeignKey(Status, on_delete=models.PROTECT, related_name='tokens_with_status_was', null=True, blank=True)
    status_history = models.ManyToManyField(Status, through='StatusHistory', related_name='tokens_in_status_history')

            
    def get_token(self):
        return f'token {self.pk} for {self.Service if self.Service else self._Service}'
    
    def __str__(self):
        return f'{self.pk}'
    
    def get_absolute_url(self):
        return reverse("token-detail", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        if self.pk:
            if self.status_was.pk != self.status.pk:
                StatusHistory.objects.create(tracked_object=self, status=self.status)
            self.status_was = Token.objects.get(pk=self.pk).status
            
        if not self.pk:
            super(Token, self).save(*args, **kwargs)
            self.status_was = self.status
            if self.status_was != self.status.pk:
                StatusHistory.objects.create(tracked_object=self, status=self.status)
            
        super(Token, self).save(*args, **kwargs)
        # # if 
        # StatusHistory.objects.create(tracked_object=self, status=self.status)
        

tokenapp/forms.py
from django import forms
from .models import Token, Service


class TokenForm(forms.ModelForm):
    class Meta:
        model = Token
        fields = ['token_time', 'token_date', 'service', 'custom_service', 'description']
        widgets = {
            'token_date': forms.DateInput(attrs={'input_type': 'date', "placeholder": 'date'}),
            'token_time': forms.TimeInput(attrs={'input_type': 'time', "placeholder": 'time'}),
            # 'service': forms.Select(choices=[(service.code, service.name) for service in Service.objects.all()], ),
            'custom_service': forms.TextInput(attrs={'input_type': 'text', "placeholder": 'other service', "id_":'custom_service_id'}),
            'description': forms.Textarea(attrs={"placeholder": 'description'}),
        }
    
    input_formats = {
            'token_date': ['%Y-%m-%d'], 
            'token_time': ['%I:%M %p'],  
        }
    

tokenapp/views.py
from django.shortcuts import render

# Create your views here.

tokenapp/templates/tokenapp/token_confirm_delete.html
{% extends "client/base.html" %}
{% block content %}
    <div class="flex">
        <div class="flex w-full flex-col max-h-fit bg-white rounded-2xl px-6 py-6 outline outline-0 space-y-1.5 md:w-full">
            <form action="">
                <div class="flex flex-col align-middle justify-center items-center">
                    <h1 class="w-fit text-2xl font-medium text-gray-800">Delete Token {{ object.id }} for {{ object.service }}!</h1>
                    <p class="w-fit text-base font-medium text-gray-600">Are you sure?</p>
                    <div class="flex flex-row space-x-6 mt-5 text-base font-medium">
                        <a class="py-1  px-4   text-gray-800 rounded-lg cursor-pointer outline outline-1 hover:bg-gray-200" href="{% url 'client:token-detail' object.id %}">Cancel</a>
                        <button class="py-1  px-4   text-white rounded-lg cursor-pointer outline outline-1 bg-gray-800 hover:bg-gray-700" type="submit">Delete</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

tokenapp/templates/tokenapp/token_detail.html
{% extends "client/base.html" %}
{% load tokenapp_extras %}
{% block content %}

<div class="flex flex-col items-center justify-center">
    <div class="flex w-fit flex-col items-center justify-center  bg-white rounded-2xl px-6 py-6 outline outline-1 md:w-1/4">
      <h1 class="w-fit text-2xl underline underline-offset-4 font-medium text-gray-800">Token {{token.id}}</h1>
      <div method="POST" class="w-full px-5  mt-3 space-y-3">

        {% for field in form %}
            <div class="flex flex-col ">
                <label class="text-sm text-gray-800 p-0.5 w-fit" id="{{ field.id_for_label }}" for="{{ field.id_for_label }}">{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}</label>
                <p class="p-1.5 rounded-lg  outline placeholder:text-gray-500 outline-0 bg-slate-50">
                    {{ object|getattr:field.html_name }}
                </p>
            </div>
        {% endfor %}
        <div class="mt-1.5 space-y-3">
            <div class="flex items-center justify-between">
            <label class="text-sm text-gray-800 p-0.5 w-fit" id="{{ field.id_for_label }}" for="{{ field.id_for_label }}">Token Status</label>
            <button id="expandButton"  onclick="toggleTimeline()">
                <svg id="chevronIcon" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-square-rounded-chevron-down-filled text-gray-800" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 2c-.218 0 -.432 .002 -.642 .005l-.616 .017l-.299 .013l-.579 .034l-.553 .046c-4.785 .464 -6.732 2.411 -7.196 7.196l-.046 .553l-.034 .579c-.005 .098 -.01 .198 -.013 .299l-.017 .616l-.004 .318l-.001 .324c0 .218 .002 .432 .005 .642l.017 .616l.013 .299l.034 .579l.046 .553c.464 4.785 2.411 6.732 7.196 7.196l.553 .046l.579 .034c.098 .005 .198 .01 .299 .013l.616 .017l.642 .005l.642 -.005l.616 -.017l.299 -.013l.579 -.034l.553 -.046c4.785 -.464 6.732 -2.411 7.196 -7.196l.046 -.553l.034 -.579c.005 -.098 .01 -.198 .013 -.299l.017 -.616l.005 -.642l-.005 -.642l-.017 -.616l-.013 -.299l-.034 -.579l-.046 -.553c-.464 -4.785 -2.411 -6.732 -7.196 -7.196l-.553 -.046l-.579 -.034a28.058 28.058 0 0 0 -.299 -.013l-.616 -.017l-.318 -.004l-.324 -.001zm-3.707 8.293a1 1 0 0 1 1.32 -.083l.094 .083l2.293 2.292l2.293 -2.292a1 1 0 0 1 1.32 -.083l.094 .083a1 1 0 0 1 .083 1.32l-.083 .094l-3 3a1 1 0 0 1 -1.32 .083l-.094 -.083l-3 -3a1 1 0 0 1 0 -1.414z" fill="currentColor" stroke-width="0"></path>
                 </svg>
            </button>
        </div>
            <div class="pl-5">
                <ol id="timeline" class="relative border-l border-gray-200 dark:border-gray-700" style="list-style: none; padding: 0;">
                    {% for item in history %}
                        <li class="mb-10 ml-4" {% if forloop.last %}style="display: block;"{% else %}style="display: none;"{% endif %}>
                            <div class="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                            <time class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">{{ item.timestamp }}</time>
                            <h3 class="text-{{ item.status.name | lower }}-text bg-{{ item.status.name | lower }}-bg py-0.5 px-4 rounded-lg w-fit">{{ item.status.name }}</h3>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
        
      </div>
      <div class="w-full flex justify-end space-x-2">
        <a class="" href="{% url "client:token-update" object.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit text-blue-400 hover:text-blue-600" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1"></path>
                <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z"></path>
                <path d="M16 5l3 3"></path>
             </svg>
        </a>
        <a class="" href="{% url "client:token-delete" object.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash text-red-400 hover:text-red-600" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M4 7l16 0"></path>
                <path d="M10 11l0 6"></path>
                <path d="M14 11l0 6"></path>
                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
            </svg>
        </a>
      </div>
    </div>
    <a href="{{request.META.HTTP_REFERER|escape}}" class="mt-5 mb-2 w-fit items-center justify-center rounded-full bg-gray-900 hover:bg-gray-800 px-5 py-1.5 font-medium text-white">
    <div class="flex items-center space-x-2 px-1">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-square-chevron-left-filled" width="18" height="18" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1 -3 3h-14a3 3 0 0 1 -3 -3v-14a3 3 0 0 1 3 -3zm-5.293 6.293a1 1 0 0 0 -1.414 0l-3 3l-.083 .094a1 1 0 0 0 .083 1.32l3 3l.094 .083a1 1 0 0 0 1.32 -.083l.083 -.094a1 1 0 0 0 -.083 -1.32l-2.292 -2.293l2.292 -2.293l.083 -.094a1 1 0 0 0 -.083 -1.32z" stroke-width="0" fill="currentColor"></path>
             </svg>
            <p>Back</p>
    </div></a>
</div>
{% endblock content %}
{% block script %}
<script>
    function toggleTimeline() {
        const timeline = document.getElementById('timeline');
        const chevronIcon = document.getElementById('chevronIcon');

        // Toggle the visibility of the timeline items
        const timelineItems = timeline.getElementsByTagName('li');
        for (let i = 0; i < timelineItems.length - 1; i++) {
            timelineItems[i].style.display = timelineItems[i].style.display === 'none' ? '' : 'none';
        }

        // Toggle the rotation of the chevron icon
        const isExpanded = timelineItems[0].style.display !== 'none';
        chevronIcon.style.transform = isExpanded ? 'rotate(180deg)' : '';
    }
</script>
{% endblock script %}

tokenapp/templates/tokenapp/token_form.html
{% extends "client/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% comment %} <div class="w-full max-w-md mx-auto">
    <form method="POST" action="" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <fieldset>
            <legend class="text-xl text-center mb-4">Book your slot</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="text-center mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Create
            </button>
        </div>
    </form>
</div> {% endcomment %}
<div class="flex items-center justify-center">
    <div class="flex max-w-fit flex-col items-center justify-center  bg-white rounded-2xl px-6 py-6 outline outline-1 md:w-fit">
      <h1 class="w-fit text-xl font-medium text-gray-800">Book your Token</h1>
      <p class="text-sm font-normal text-gray-600 mb-2">Fill these fields for your token</p>
      <!-- <h1>Login</h1> -->
      <form method="POST" class="w-fit px-5 py-2 mt-1 space-y-3">
        {% csrf_token %}
        
        {% comment %} <span class="max-w-10 font-light text-sm">{{ form.non_field_errors }}</span> {% endcomment %}
        <div class="max-w-md"> <!-- Set the maximum width here -->
            <span class="font-light text-sm">{{ form.non_field_errors }}</span>
        </div>
        {% for field in form %}
            <div>
                <label class="text-sm text-gray-800 p-0.5 w-fit" for="{{ field.id_for_label }}">{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}</label>
                    {% if field.html_name == 'service' %}
                        <select  name="{{ field.html_name }}" id="" placeholder="{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}" class="p-1.5 rounded-lg w-full outline placeholder:text-gray-500 outline-0 bg-slate-50 ">
                            {% for id, name in field.field.choices %}
                            <option value="{{ id }}">{{name | title }}</option>
                            {% endfor %}
                        </select>
                    {% elif field.html_name == 'description' %}
                        <textarea  name="{{ field.html_name }}" id="" placeholder="{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}" class="p-1.5 rounded-lg w-full outline placeholder:text-gray-500 outline-1  bg-slate-50"></textarea>
                    {% else %}
                        <input type="{{ field.field.widget.attrs.input_type }}" name="{{ field.html_name }}" id="" placeholder="{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}" class="p-1.5 rounded-lg w-full outline placeholder:text-gray-500 outline-0 bg-slate-50">
                    {% endif %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <li class="text-sm text-red-500">{{ error|escape }}</li>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}
        <div class="flex flex-col items-center">
          <button type="submit" class=" mt-2 mb-2 w-fit items-center justify-center rounded-full bg-gray-900  hover:bg-gray-800 px-5 py-1.5 font-semibold text-white">Book Token</button>
          {% comment %} <span class="cursor-pointer text-sm text-gray-700 hover:text-blue-600"><a href="{% url 'login' %}">Already have an account ?</a></span> {% endcomment %}
        </div>
      </form>
    </div>
</div>

{% endblock content %}

{% comment %} <select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select> {% endcomment %}