client/urls.py
from django.urls import path
from .views import (
    TokenListView, 
    TokenDetailView, 
    TokenCreateView, 
    TokenUpdateView, 
    TokenDeleteView,
    UserTokenListView,
    ProfileView,
    ClientProfileUpdateView,
    UserUpdateView
)
from . import views

app_name = 'client'

urlpatterns = [
    path('', TokenListView.as_view(), name='token-home'),
    path('token/', UserTokenListView.as_view(), name='token-list'),
    path('token/<int:pk>/', TokenDetailView.as_view(), name='token-detail'),
    path('token/new/', TokenCreateView.as_view(), name='token-create'),
    path('token/<int:pk>/update/', TokenUpdateView.as_view(), name='token-update'),
    path('token/<int:pk>/delete/', TokenDeleteView.as_view(), name='token-delete'),
    path('profile/', ProfileView.as_view(), name='user-profile'),
    path('profile/user-update/', UserUpdateView.as_view(), name='user-update'),
    path('profile/profile-update/', ClientProfileUpdateView.as_view(), name='user-profile-update'),
    path('about/', views.about, name='token-about'),
]

slot_management/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from client import views as client_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('client.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login/', user_views.CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    # path('profile/', user_views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# from django.urls import path
# from . import views

# urlpatterns = [
#     path("api/get_subroles/", views.get_subroles, name="get_subroles"),
# ]

client/models.py
from django.db import models
from users.models import BaseProfile
import uuid


class ClientProfile(BaseProfile):
    client_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    mobile_verified = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username}\'s Profile'

client/forms.py
from django import forms
from .models import ClientProfile
from users.forms import ProfileUpdateForm


class ClientProfileForm(forms.ModelForm):
    class Meta:
        model = ClientProfile
        fields = ['birth_date', 'address', 'pincode', 'mobile_number']
        widgets = {
            'birth_date': forms.DateInput(attrs={'input_type': 'date', "placeholder": 'birth date'}),
            'mobile_number': forms.TextInput(attrs={"placeholder": 'mobile nubmer'}),
        }

class ClientProfileUpdateForm(ProfileUpdateForm):
    class Meta(ProfileUpdateForm.Meta):
        model = ClientProfile
        # fields = '__all__'

client/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from users.models import CustomUser, Role
from client.forms import ClientProfileForm, ClientProfileUpdateForm
from users.forms import UserUpdateForm
from client.models import ClientProfile
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from tokenapp.models import Token, Status, StatusHistory
from tokenapp.forms import TokenForm
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)
from PIL import Image
from django.core.files.base import ContentFile
from io import BytesIO
import uuid
from django.utils.text import slugify
from django.core.files.storage import FileSystemStorage


class TokenListView(ListView):
    model = Token
    # template_name = 'client/home.html'  
    context_object_name = 'tokens'
    # ordering = ['token_time']
    paginate_by = 10
    
    
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            if user.role.name == 'USER':
                status = Status.objects.get(name='Pending')
                queryset = Token.objects.filter(user_id=user.id, status=status).order_by('-token_time')

            elif user.role.name == 'STAFF':
                queryset = Token.objects.filter(assigned_staff=user.id).order_by('-token_time')
                
            elif  user.role.name == 'ADMIN':
                queryset = Token.objects.all()
        else:
            queryset = Token.objects.none()
            
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_empty'] = not Token.objects.filter(user=self.request.user).exists()
        return context
    
    def get_template_names(self):
        if self.request.user.role.name in ('ADMIN', 'STAFF'):
            return ['client/staff_home.html']
        else:
            return ['client/home.html']


class UserTokenListView(ListView, LoginRequiredMixin):  
    model = Token
    template_name = 'client/user_tokens.html'
    context_object_name = 'tokens'
    ordering = ['token_time']
    paginate_by = 10
    
    def get_queryset(self):
        user = self.request.user
        return Token.objects.filter(user_id=user.id).order_by('-token_time')
    

class TokenDetailView(DetailView):
    model = Token
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TokenForm()
        context['history'] = StatusHistory.objects.filter(tracked_object=self.get_object()).order_by('timestamp')
        return context
    

class TokenCreateView(LoginRequiredMixin, CreateView):
    model = Token
    form_class = TokenForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('client:token-list')

class TokenUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Token
    form_class = TokenForm
    
    def get_initial(self):
        initial = super(TokenUpdateView, self).get_initial()
        initial['token_date'] = self.object.token_date.strftime('%Y-%m-%d')
        initial['token_time'] = self.object.token_time.strftime('%H:%M:%S')
        return initial
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Token updated successfully")
        return super().form_valid(form)
    
    def test_func(self):
        Token = self.get_object()
        if self.request.user == Token.user:
            return True
        return False
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_update'] = True
        return context
    
    def get_success_url(self):
        return reverse_lazy('client:token-detail', kwargs={'pk': self.object.pk})


class TokenDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Token
    success_url = '/'
    
    def test_func(self):
        Token = self.get_object()
        if self.request.user == Token.user:
            return True
        return False
    
    
class ProfileView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'client/client_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = ClientProfile.objects.get(user=self.request.user)
        context['u_form'] = UserUpdateForm()
        context['p_form'] = ClientProfileForm()
        return context
    
    def test_func(self):
        try:
            ClientProfile.objects.get(user=self.request.user)
            return True
        except ClientProfile.DoesNotExist:
            return False


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = UserUpdateForm
    success_url = reverse_lazy('client:user-profile')
    # template_name = 'client/clientprofile_form.html'
    
    def get_object(self, queryset=None):
        return get_object_or_404(CustomUser, username=self.request.user.username)

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "User updated successfully")
        return super().form_valid(form)
 
    def test_func(self):
        CustomUser = self.get_object()
        if self.request.user == CustomUser:
            return True
        return False
    
    
class ClientProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ClientProfile
    form_class = ClientProfileUpdateForm
    success_url = reverse_lazy('client:user-profile')
    template_name = 'client/clientprofile_form.html'
    
    def get_object(self, queryset=None):
        return get_object_or_404(ClientProfile, user=self.request.user)
    
    def get_initial(self):
        initial = super(ClientProfileUpdateView, self).get_initial()
        birth_date = self.object.birth_date
        if birth_date:
            initial['birth_date'] = birth_date.strftime('%Y-%m-%d')
        return initial
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save(commit=False)
        if 'image' in self.request.FILES: 
            img = Image.open(self.request.FILES['image'])
            width, height = img.size
            if width > 300 and height > 300:
                img.thumbnail((width, height))

            if height < width:
                left = (width - height) / 2
                right = (width + height) / 2
                top = 0
                bottom = height
                img = img.crop((left, top, right, bottom))

            elif width < height:
                left = 0
                right = width
                top = 0
                bottom = width
                img = img.crop((left, top, right, bottom))

            if width > 300 and height > 300:
                img.thumbnail((300, 300))

            buffer = BytesIO()
            uid = str(uuid.uuid4())[:8]
            filename = f"{slugify(self.request.user.username)}_{uid}.jpeg"
            img.save(buffer, format='JPEG')
            form.instance.image = ContentFile(buffer.getvalue(), filename)
            # form.instance.image.save(filename, ContentFile(buffer.getvalue(), filename), save=False)
            
        messages.success(self.request, "Profile updated successfully")
        return super().form_valid(form)
    
    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     if form.is_valid():
    #         messages.success(self.request, "Profile updated successfully")
    #     else:
    #         print(form.errors)
    #     return super().form_valid(form)
    
    def test_func(self):
        ClientProfile = self.get_object()
        if self.request.user == ClientProfile.user:
            return True
        return False
    

def about(request):
    return render(request, 'token/about.html')

client/templates/client/about.html
{% extends "client/base.html" %}
{% block content %}
    <h1>About Page</h1> 
{% endblock content %}

client/templates/client/client_profile.html
{% extends "client/base.html" %}
{% load tokenapp_extras %}
{% block content %}
<div class="flex flex-col items-center justify-center">
    <div class="flex min-w-fit flex-col items-center justify-center  bg-white rounded-2xl px-6 py-6 outline outline-1 md:w-1/5">
        <img class='w-28 h-28 rounded-full ' src="{{profile.image.url}}" alt="user.id">
      <h1 class="w-fit text-xl font-medium text-gray-800">{{user.username|title}}</h1>
      <h1 class="w-fit text-sm font-light text-gray-600">ID : {{profile.client_id}}</h1>
      <h1 class="w-fit text-base mt-6 font-medium text-gray-800">Account Details</h1>
      <div method="POST" class="w-full px-5  mt-1 space-y-2">
          
          {% for field in u_form %}
          <div class="flex flex-row items-center  ">
                <label class="text-sm text-gray-800 p-0.5 w-fit" id="{{ field.id_for_label }}" for="{{ field.id_for_label }}">{{ field.field.widget.attrs.placeholder|default:field.html_name|title }} : </label>
                <p class="p-1.5 rounded-lg   bg-slate-50">
                    {{ user|getattr:field.html_name }}
                </p>
            </div>
            {% endfor %}
        </div>
        <div class="w-full flex justify-end space-x-2">
            <a class="" href="{% url "client:user-update" %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit text-blue-400 hover:text-blue-600" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1"></path>
                    <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z"></path>
                    <path d="M16 5l3 3"></path>
                 </svg>
            </a>
          </div>
        <h1 class="w-fit text-base mt-6 font-medium text-gray-800">User Details</h1>
        <div method="POST" class="w-full px-5  mt-1 space-y-2">
        {% for field in p_form %}
            <div class="flex flex-row items-center  ">
                <label class="text-sm text-gray-800 p-0.5 w-fit" id="{{ field.id_for_label }}" for="{{ field.id_for_label }}">{{ field.field.widget.attrs.placeholder|default:field.html_name|title }} : </label>
                <p class="p-1.5 rounded-lg   bg-slate-50">
                    {{ profile|getattr:field.html_name }}
                </p>
            </div>
            {% endfor %}
        </div>
      <div class="w-full flex justify-end space-x-2">
        <a class="" href="{% url "client:user-profile-update" %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit text-blue-400 hover:text-blue-600" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1"></path>
                <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z"></path>
                <path d="M16 5l3 3"></path>
             </svg>
        </a>
        {% comment %} <a class="" href="{% url "client:user-delete" user.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash text-red-400 hover:text-red-600" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M4 7l16 0"></path>
                <path d="M10 11l0 6"></path>
                <path d="M14 11l0 6"></path>
                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
            </svg>
        </a> {% endcomment %}
      </div>
    </div>
    <a href="{{request.META.HTTP_REFERER|escape}}" class="mt-5 mb-2 w-fit items-center justify-center rounded-full bg-gray-900 hover:bg-gray-800 px-5 py-1.5 font-medium text-white">
    <div class="flex items-center space-x-2 px-1">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-square-chevron-left-filled" width="18" height="18" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1 -3 3h-14a3 3 0 0 1 -3 -3v-14a3 3 0 0 1 3 -3zm-5.293 6.293a1 1 0 0 0 -1.414 0l-3 3l-.083 .094a1 1 0 0 0 .083 1.32l3 3l.094 .083a1 1 0 0 0 1.32 -.083l.083 -.094a1 1 0 0 0 -.083 -1.32l-2.292 -2.293l2.292 -2.293l.083 -.094a1 1 0 0 0 -.083 -1.32z" stroke-width="0" fill="currentColor"></path>
             </svg>
            <p>Back</p>
    </div></a>
</div>
{% endblock content %}

client/templates/client/clientprofile_form.html
{% extends "client/base.html" %}
{% load tokenapp_extras %}
{% load crispy_forms_tags %}
{% block content %}

<div class="flex items-center justify-center">
    <div class="flex max-w-fit flex-col items-center justify-center  bg-white rounded-2xl px-6 py-6 outline outline-1 md:w-fit">
      <form method="POST" enctype="multipart/form-data" class="w-fit px-5 py-2 mt-1 space-y-3">
        {% csrf_token %}
        
        <div class="max-w-md">
            <span class="font-light text-sm">{{ form.non_field_errors }}</span>
        </div>
        {% for field in form %}
            <div class="flex flex-col">
                <label class="text-sm text-gray-800 p-0.5 w-fit" id="{{ field.id_for_label }}" for="{{ field.id_for_label }}">{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}</label>
                    {% if field.html_name == 'image' %}
                          <div class="">
                            <img class='w-16 h-1w-16 rounded-full ' src="{{object.image.url}}" alt="object.id">
                            <input type="file" name="{{field.html_name}}" accept="image/*" id="{{ field.id_for_label }}" class="text-sm p-1.5 rounded-lg  placeholder:text-gray-500  bg-slate-50">
                          </div>
                    {% elif field.html_name == 'address' %}
                        <textarea  name="{{ field.html_name }}"  id="" placeholder="{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}" class="p-1.5 rounded-lg w-full outline placeholder:text-gray-500 outline-1  bg-slate-50">{{ field.value|default:'' }}</textarea>
                    {% else %}
                        <input type="{{ field.field.widget.attrs.input_type }}" value="{{ field.value|default:'' }}" name="{{ field.html_name }}" id="{{ field.field.widget.attrs.id_|default:''}}" placeholder="{{ field.field.widget.attrs.placeholder|default:field.html_name|title }}" class="p-1.5 rounded-lg w-full outline placeholder:text-gray-500 outline-0 bg-slate-50">
                    {% endif %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <li class="text-sm text-red-500">{{ error|escape }}</li>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}
        <div class="flex flex-col items-center">
          <button type="submit" class=" mt-2 mb-2 w-fit items-center justify-center rounded-full bg-gray-900  hover:bg-gray-800 px-5 py-1.5 font-semibold text-white">Update Profile</button>
        </div>
      </form>
    </div>
</div>
{% endblock content %}

{% block script %}

{% endblock script %}

client/templates/client/home.html
{% extends "client/base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        
        <div class="flex">
            <div class="flex w-full flex-col max-h-fit bg-white rounded-2xl px-6 py-6 outline outline-0 space-y-1.5 md:w-full">
                {% if not tokens %}
                <div class="flex flex-col align-middle justify-center items-center">
                    {% if is_empty and user.role.name == 'USER' %}
                        <h1 class="w-fit text-2xl font-medium text-gray-800">Seamless token booking anywhere anytime !</h1>
                        <a class="py-2 mt-3 px-4 text-base font-medium text-white rounded-lg cursor-pointer bg-gray-800" href="{% url 'client:token-create' %}">Book Now</a>
                    {% else %}
                        <h1 class="w-fit text-xl font-medium text-gray-800">{% if user.role.name == 'STAFF' %}Your have no assigned Tokens{% else %}You have no upcoming Tokens{% endif %}</h1>
                        <p class="text-sm font-normal text-gray-600 mb-2">{% if user.role.name == 'STAFF' %}Explore your assigned Tokens{% else %}Explore your bookings{% endif %}</p>
                        <div class="flex justify-end">
                            <a class="py-1 mt-1 px-3 text-sm font-medium text-white rounded-lg cursor-pointer bg-gray-800" href='{% url 'client:token-list' %}'>My Tokens</a>
                        </div>
                    {% endif %}
                </div>
                {% else %}
                    <div class="flex justify-between items-center">
                        <h1 class="w-fit text-xl font-medium text-gray-800">{% if user.role.name == 'STAFF' %}Pending Tokens{% else %}Upcoming Tokens{% endif %}</h1>
                        {% if user.role.name == 'USER' %}
                        {% comment %} <div class="flex items-center space-x-3"> {% endcomment %}
                            <a class="flex items-center py-1.5 mt-1 px-3 text-sm font-medium text-white rounded-lg cursor-pointer bg-gray-800" href='{% url 'client:token-create' %}'>
                                <svg xmlns="http://www.w3.org/2000/svg" class="mr-1.5 icon icon-tabler icon-tabler-plus" width="18" height="18" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M12 5l0 14"></path>
                                    <path d="M5 12l14 0"></path>
                                 </svg>
                                New Token
                            </a>
                            {% comment %} <svg xmlns="http://www.w3.org/2000/svg" class=" icon icon-tabler icon-tabler-dots-vertical" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
                                <path d="M12 19m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
                                <path d="M12 5m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
                             </svg> {% endcomment %}
                        {% comment %} </div> {% endcomment %}
                        {% endif %}
                    </div>
                        {% for token in tokens %}
                            <a href="{% url "client:token-detail" token.pk  %}">
                                <div class="flex flex-row space-x-5 py-1.5 px-3 text-sm font-normal items-center bg-slate-100 hover:bg-slate-200 rounded-lg">
                                    <p class=" text-slate-900">{{ token.id }} - {{ token.service }}</p>
                                    <p class="text-{{ token.status_id | lower }}-text bg-{{ token.status_id | lower }}-bg py-0.5 px-4 rounded-lg w-fit">{{ token.status_id}}</p>
                                </div>
                            </a>
                        {% endfor %}
                        <div class="flex justify-center">
                            <a class="py-1.5 mt-5 px-5 text-sm font-medium text-white rounded-lg cursor-pointer bg-gray-800" href='{% url 'client:token-list' %}'>My Tokens</a>
                        </div>
                {% endif %} 
            </div>
        </div>
    {% endif %}
{% endblock content %}
<!--https://freefrontend.com/tailwind-charts-and-graphs/-->

client/templates/client/staff_home.html
{% extends "client/home.html" %}
{% block content %}
    {% if user.role.name == 'STAFF' %}
        {{ block.super }}
    {% endif %}
{% endblock content %}

client/templates/client/token_form.html
{% extends "client/base.html" %}
{% block content %}
<div class="w-full max-w-md mx-auto">
    <form method="POST" action="" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <fieldset>
            <legend class="text-xl text-center mb-4">Book your slot</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="text-center mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Create
            </button>
        </div>
    </form>
</div>

{% endblock content %}